### ISSUE TITLE
Robot test results cannot be written to report portal web site with robot 4.0.2 (report-agent: 5.1.1)

### ISSUE THREAD

**Issue by doguz2509** [reportportal/agent-Python-RobotFramework#107]
--
Error: 

20210520 15:49:18.285 | ERROR | Taking listener 'module' into use failed: Listener 'robotframework_reportportal.listener' does not have mandatory 'ROBOT_LISTENER_API_VERSION' attribute.
-- | -- | --

**Package versions**
robotframework-reportportal - 5.1.1
robotframework - 4.0.2

**Comment by iivanou** [comment]
@doguz2509 , Please check your Python environment. The [requested attributed exists](https://github.com/reportportal/agent-Python-RobotFramework/blob/master/robotframework_reportportal/listener.py#L33) in the agent listener code. I'm not sure what to suggest because the specified combination of agent and robot framework versions works well on my side.

**Comment by doguz2509** [comment]
usage mistake after upgrade
